---
version: "3.3"

networks:
  webfrontend:

services:
  traefik:
    image: "traefik"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.http.address=:80"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - webfrontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./webserver/auth:/auth
    restart: always

  webserver1:
    container_name: webserver1
    image: nginx
    volumes:
      - ./webserver/mywebserver1:/usr/share/nginx/html
    networks:
      - webfrontend
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.mywebserver1.entryPoints=http
      - traefik.http.services.mywebserver1.loadbalancer.server.port=80
      - traefik.http.routers.mywebserver1.rule=Host(`az.frotmail.nl`)
      - traefik.http.middlewares.test-auth.basicauth.usersfile=/auth/web.htpasswd
      - traefik.http.routers.mywebserver1.middlewares=test-auth