  webserver:
    container_name: webserver
    image: nginx
    volumes:
      - ./webserver/:/usr/share/nginx/html
    networks:
      - webfrontend
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.mywebserver.entryPoints=https
      - traefik.http.services.mywebserver.loadbalancer.server.port=80

      # - traefik.http.routers.mywebserver.rule=Host(`myweb.local`)
      # - traefik.http.routers.mywebserver.rule=ClientIP(`10.0.0.0/8`)
      - traefik.http.routers.mywebserver.rule=PathPrefix(`/mywebserver`)

      # - traefik.http.middlewares.my-strip.stripprefix.prefixes=/mywebserver
      ## https://doc.traefik.io/traefik/migration/v1-to-v2/#strip-and-rewrite-path-prefixes
      # - traefik.http.routers.mywebserver.middlewares=my-strip

      # - traefik.http.routers.mywebserver.priority=50
