---
version: "3.3"

networks:
  webfrontend:

services:
  traefik:
    image: "traefik"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.http.address=:80"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - webfrontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  webserver1:
    container_name: webserver1
    image: nginx
    volumes:
      - ./webserver/:/usr/share/nginx/html
    networks:
      - webfrontend
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.mywebserver1.entryPoints=https
      - traefik.http.services.mywebserver1.loadbalancer.server.port=80
      - traefik.http.routers.mywebserver1.rule=PathPrefix(`/mywebserver1`)

  webserver2:
    container_name: webserver2
    image: nginx
    volumes:
      - ./webserver/:/usr/share/nginx/html
    networks:
      - webfrontend
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.mywebserver2.entryPoints=https
      - traefik.http.services.mywebserver2.loadbalancer.server.port=80
      - traefik.http.routers.mywebserver2.rule=PathPrefix(`/mywebserver2`)
      - traefik.http.routers.mywebserver2.middlewares=my-strip
      - traefik.http.middlewares.my-strip.stripprefix.prefixes=/mywebserver2
      ## https://doc.traefik.io/traefik/migration/v1-to-v2/#strip-and-rewrite-path-prefixes
      ## Andere 'rule' opties...
      # - traefik.http.routers.mywebserver.rule=Host(`myweb.local`)
      # - traefik.http.routers.mywebserver.rule=ClientIP(`10.0.0.0/8`)
      # - traefik.http.routers.mywebserver.rule=ClientIP(`10.0.0.0/8`) && Host(`myweb.local`)
      # - traefik.http.routers.mywebserver.priority=50
