---
version: "3.3"

networks:
  webfrontend:

services:
  traefik:
    image: "traefik"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.http.address=:80"
      - "--entryPoints.https.address=:443"
      - "--entryPoints.https.http.tls=true"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - webfrontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/traefik/certs:/certs
    restart: always

  webserver1:
    container_name: webserver1
    image: nginx
    volumes:
      - ../No-Traefik/webserver1/:/usr/share/nginx/html
    networks:
      - webfrontend
    ports:
      - 8081:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.webserver1.entryPoints=https
      - traefik.http.services.webserver1.loadbalancer.server.port=80
      - traefik.http.routers.webserver1.rule=Host(`web1.az.frotmail.nl`)
    restart: always

  webserver2:
    container_name: webserver2
    image: nginx
    volumes:
      - ../No-Traefik/webserver2/:/usr/share/nginx/html
    networks:
      - webfrontend
    ports:
      - 8082:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.webserver2.entryPoints=https
      - traefik.http.services.webserver2.loadbalancer.server.port=80
      - traefik.http.routers.webserver2.rule=Host(`web2.az.frotmail.nl`)
    restart: always
